# Generated by Django 4.2.1 on 2023-05-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('fname', models.CharField(max_length=220)),
                ('lname', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=20)),
                ('College', models.TextField()),
                ('course', models.TextField()),
                ('passyear', models.CharField(max_length=10)),
                ('profilePic', models.FileField(upload_to='media-root/profiles')),
            ],
        ),
        migrations.CreateModel(
            name='teacherProfile',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('fname', models.CharField(max_length=220)),
                ('lname', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=20)),
                ('College', models.TextField()),
                ('course', models.TextField()),
                ('idproof', models.FileField(upload_to='media-root/idproof')),
                ('profilePic', models.FileField(upload_to='media-root/teacherprofiles')),
            ],
        ),
    ]
