# Generated by Django 4.2.1 on 2023-05-11 05:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvents',
            fields=[
                ('peid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('fronposter', models.FileField(upload_to='media-root/ProjectPoster')),
                ('eventdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('eventtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEventEntry',
            fields=[
                ('peeid', models.AutoField(primary_key=True, serialize=False)),
                ('peinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherdashboard.projectevents')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
